# Do you want to report only on the local machine or sent to the server?
remote: false

# Give a name to the experiment and run
experiment_name: "my_favorite_experiment"
run_name: "my_favorite_run"
run_description: "This is my favorite experiment"
run_tags:
  my_favorite_tag: "my_favorite_tag_value"
  another_favorite_tag: "another_favorite_tag_value"

# This is for the registered model
model_description: "This is my favorite model"
model_name: "my_favorite_model"
model_tags:
  my_favorite_tag: "my_favorite_tag_value"
  another_favorite_tag: "another_favorite_tag_value"

# This is specific to the model version
model_version_description: "This is my favorite model version"
model_version_alias: "my_favorite_model_alias"
model_version_tags:
  my_favorite_tag: "my_favorite_tag_value_for_my_favorite_model_version"
  another_favorite_tag: "another_favorite_tag_value_for_my_favorite_model_version"

# Dataset (in our case metadata)
dataset_name: "my_favorite_dataset"

# Organisation of the artifacts
model_artifact_path: "model"
metadata_artifact_path: "metadata"

